### ISSUE TITLE
Some naming conventions

### ISSUE THREAD

**Issue by sammy007** [gabstv/go-monero#2]
It would be nice to rename current `Getheight`, `Getaddress` to `GetHeight`, `GetAddress`.

**Comment by sammy007** [comment]
`Getbalance` also.

**Comment by gabstv** [comment]
Initially I was converting the names like:  
*getbalance -> Getbalance*  
*start_mining -> StartMining*  

But I admit that the first RPC functions look weird. It looks like the RPC devs were not following a convention before, but then they decided to add the undercore on the newer methods (and kept the older functions unchanged to avoid breaking implementations).
